@extends('be.master')
@section('sidebar')
    @include('be.components.sidebar')
@endsection
@section('header')
    @include('be.components.header')
@endsection
@section('dailysales')
    @include('be.components.dailysales')
@endsection
@section('monthlysales')
    @include('be.components.monthlysales')
@endsection
@section('yearlysales')
    @include('be.components.yearlysales')
@endsection
@section('statisticyear')
    @include('be.components.statisticyear')
@endsection
@section('socialmedia')
    @include('be.components.socialmedia')
@endsection
@section('ratinglist')
    @include('be.components.ratinglist')
@endsection
@section('recentusers')
    @include('be.components.recentusers')
@endsection
