@extends('be.master')
@section('sidebar')
    @include('be.sidebar')
@endsection
@section('header')
    @include('be.header')
@endsection
@section('dailysales')
    @include('be.dailysales')
@endsection
@section('monthlysales')
    @include('be.monthlysales')
@endsection
@section('yearlysales')
    @include('be.yearlysales')
@endsection
