@extends('be.master')
@section('sidebar')
    @include('be.sidebar')
@endsection
@section('header')
    @include('be.header')
@endsection
@section('pelanggans')
    @include('be.pelangganstable.pelanggans')
@endsection
