@extends('fe.master')
@section('navbar')
    @include('fe.components.navbar')
@endsection
@section('features')
    @include('fe.components.features')
@endsection
@section('testimonies')
    @include('fe.components.testimonies')
@endsection
